# Generated by Django 2.0 on 2017-12-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='乘客名称')),
                ('phone_number', models.CharField(max_length=11, verbose_name='电话号码')),
            ],
            options={
                'verbose_name': '乘客信息',
                'verbose_name_plural': '乘客信息',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='车票名称')),
                ('time', models.DateTimeField(verbose_name='车票购买时间')),
                ('brief', models.TextField(max_length=300, verbose_name='车票信息')),
                ('seats', models.IntegerField(default=0, verbose_name='剩余座位')),
            ],
            options={
                'verbose_name': '车票信息',
                'verbose_name_plural': '车票信息',
            },
        ),
    ]
