# Generated by Django 2.0 on 2017-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(verbose_name='车票出发时间'),
        ),
    ]
