# Generated by Django 2.0 on 2017-12-11 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_tickets_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ticket_name',
            field=models.CharField(default=' ', max_length=30, verbose_name='购买车票名称'),
        ),
        migrations.AddField(
            model_name='person',
            name='ticket_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 21, 30, 40, 636432), verbose_name='购买车票时间'),
        ),
    ]
